### ISSUE TITLE
active_power - unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by djsuszi** [szczeles/toolbelt#14]
Sometimes I get:
```
2021-05-04 07:45:47,718 Pushing 2 records to PVOutput
Traceback (most recent call last):
  File "./main.py", line 62, in <module>
    output[1].save(data_to_push)
  File "/home/xxx/solar/toolbelt/huawei-solar/api/pvoutput.py", line 94, in save
    for s in chunk
  File "/home/xxx/solar/toolbelt/huawei-solar/api/pvoutput.py", line 94, in <listcomp>
    for s in chunk
  File "/home/xxx/solar/toolbelt/huawei-solar/api/fusionsolar.py", line 20, in get_current_power_w
    return self.values["active_power"] * 1000
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
probably sometimes Huawei doesn't return all values, there were some
something similar to
https://github.com/szczeles/toolbelt/pull/6

**Comment by djsuszi** [comment]
but I'm not sure how to handle this,
maybe it's connected with some problems on eu5.fusionsolar.huawei.com side

**Comment by szczeles** [comment]
Good catch! I faced this already before - even while getting some historical data (like all the signals for some past date), almost all the records were consistent except for two, missing some values, so I believe they just have some gaps in the data :/

That's also why I introducted this loop: https://github.com/szczeles/toolbelt/blob/master/huawei-solar/api/fusionsolar.py#L175 - that adds nulls on non-existing signals, otherwise export to Postgres was failing :/

I believe there is nothing we can do about missing data except for retrying, I suggest you to add some restart policy for your script :-)

**Comment by djsuszi** [comment]
yesterday crash:
```
1620222300 {'a_i': 1.811, 'b_i': 1.815, 'c_i': 1.843, 'pv1_i': 2.23, 'pv2_i': 1.93, 'power_factor': 1.0, 'elec_freq': 50.0, 'active_power': 1.326, 'mppt_power': 1.381, 'reactive_power': 0.002, 'day_cap': 23.15, 'pv1_u': 340.5, 'pv2_u': 327.6}
1620222600 {'a_i': 2.546, 'b_i': 2.564, 'c_i': 2.581, 'pv1_i': 3.45, 'pv2_i': 2.48, 'power_factor': 1.0, 'elec_freq': 49.98, 'active_power': 1.874, 'mppt_power': 1.938, 'day_cap': 23.28, 'pv1_u': 334.8, 'pv2_u': 328.7, 'reactive_power': None}
1620222900 {'day_cap': 23.45, 'pv1_u': 335.7, 'pv2_u': 337.8, 'a_i': None, 'b_i': None, 'c_i': None, 'power_factor': None, 'elec_freq': None, 'active_power': None, 'reactive_power': None, 'mppt_power': None, 'pv1_i': None, 'pv2_i': None}
2021-05-05 15:55:50,102 Pushing 2 records to PVOutput
```
and today the same record
```
ts:%s value=%s 1620222900 {'a_i': 2.646, 'b_i': 2.656, 'c_i': 2.694, 'pv1_i': 3.52, 'pv2_i': 2.59, 'power_factor': 1.0, 'elec_freq': 49.98, 'active_power': 1.956, 'mppt_power': 2.023, 'reactive_power': 0.003, 'day_cap': 23.45, 'pv1_u': 335.7, 'pv2_u': 337.8}
```
maybe it's getting data to often, when not all data are in the system ?

**Comment by szczeles** [comment]
Oh, that is good point! I have checked the data in my PSQL DB and there is a lot of data missing :/ I will add some logic to handle late data on the API

**Comment by cvandend** [comment]
I've just started using this script and I am also getting this error. Is there a way to get around it?

**Comment by szczeles** [comment]
@cvandend Hm, I didn't see this issue for months, so I assumed Fusionsolar fixed it already, but apparently I was lucky ;-)

Could you please start the app in debug mode (`--verbose`) and attach the logs? Please drop any identifiers (like station id and session token)

**Comment by cvandend** [comment]
@szczeles will do, restarting now with --verbose. Btw, is there a way to also get and upload to pvoutput the energy/power used? I'm missing this to see my consumption/import/export figures.

**Comment by szczeles** [comment]
@cvandend If this is available in one signalset from fusionsolar then sure, you should be able to extend it in this place:

https://github.com/szczeles/toolbelt/blob/master/huawei-solar/api/pvoutput.py#L98

However, I don't have device measuring the power used/exported-to-grid, so can't help on that...
