### ISSUE TITLE
api.fusionsolar.FusionSolarException: Invalid response code: 500

### ISSUE THREAD

**Issue by lampra1** [szczeles/toolbelt#17]
how do I debug this?

**Comment by szczeles** [comment]
Hey @lampra1, please attach the entire traceback of the exception

**Comment by lampra1** [comment]
Hi @szczeles 
Here is the info I could obtain. If more is needed, please let me know how to obtain the info.
This is the same either with docker or directly running. 
```
$ python3 main.py --fusionsolar-user 'XXXXXXX' --fusionsolar-password 'XXXXXXXX' --pvoutput-api-key XXXXXXXXXXXXXXXXXX --pvoutput-system-id XXXXXXX --start-date 2021-08-01
2021-10-02 10:57:13,123 Backing off call_api(...) for 0.2s (api.fusionsolar.FusionSolarException: Invalid response code: 500)
2021-10-02 10:57:13,558 Backing off call_api(...) for 0.9s (api.fusionsolar.FusionSolarException: Invalid response code: 500)
2021-10-02 10:57:14,808 Backing off call_api(...) for 0.1s (api.fusionsolar.FusionSolarException: Invalid response code: 500)
2021-10-02 10:57:15,232 Backing off call_api(...) for 2.3s (api.fusionsolar.FusionSolarException: Invalid response code: 500)
2021-10-02 10:57:17,956 Backing off call_api(...) for 7.0s (api.fusionsolar.FusionSolarException: Invalid response code: 500)
^CTraceback (most recent call last):
  File "/home/dlaptop/.local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 107, in call_api
    raise FusionSolarException(f"Invalid response code: {response.status_code}")
api.fusionsolar.FusionSolarException: Invalid response code: 500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    devices = fusionsolar.list_devices()
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 153, in list_devices
    "rest/neteco/web/config/device/v1/device-list", params={'conditionParams.parentDn': self.get_station_id()}
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 146, in get_station_id
    company_info = self.call_api("rest/neteco/web/organization/v2/company/current")
  File "/home/dlaptop/.local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 110, in call_api
    self.login()
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 140, in login
    self.station = self.get_station_id()
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 148, in get_station_id
    station_info = self.call_api('rest/neteco/web/config/domain/v1/power-station/station-list', params={'params.parentDn': company_id})
  File "/home/dlaptop/.local/lib/python3.8/site-packages/backoff/_sync.py", line 112, in retry
    time.sleep(seconds)
KeyboardInterrupt
```

**Comment by szczeles** [comment]
Hmm, interesting. It looks that it fails during listing the devices, so I suspect login credentials issue. I will add today one small code change to increase verbosity so you can get more insights on the issue.

**Comment by szczeles** [comment]
@lampra1 Please try now using the master code with `--verbose` flag. If the verbose messages will not reveal the issue, feel free to paste these here so I can have a look

**Comment by lampra1** [comment]
Hi thanks again.  To my knowledge there is only one company and one plant. 
At least this is what I get at the Plants -> Device management

It seems that `/rest/neteco/web/organization/v2/company/current` returns the `moDn`
Though, `power-station/station-list` string is nowhere to be found in the browser queries. I can only see a `stationkey` in the `rest/neteco/web/config/device/v1/device-list` call which is the same both for the dongle and the inverter.

Now, if I modify the code to set static `company_id = "NE=XXXXXXX"` & `station_info = "NE=XXXXXXXX"` @ `def get_station_id(self):` I can move on.
At `def list_devices(self):` I set static parameters as: 
`rest/neteco/web/config/device/v1/device-list?conditionParams.checkShareStationDn=NE=XDongleX&conditionParams.parentDn=NE=XDongleX`
and also at `"rest/pvms/web/device/v1/device-statistics-signal",
            params={"deviceDn":"NE=XInverter"},`

Then the script executes I see the data, 
```...
2021-10-07 23:52:13,638 Starting new HTTPS connection (1): eu5.fusionsolar.huawei.com:443
2021-10-07 23:52:13,942 https://eu5.fusionsolar.huawei.com:443 "GET /rest/pvms/web/device/v1/device-statistics-signal?deviceDn=NE%3DXXXXXXXX HTTP/1.1" 200 None
2021-10-07 23:52:13,947 Available signals: [Grid phase A voltage (V), Grid phase B voltage (V), Grid phase C voltage (V), Grid phase A current (A), Grid phase B current (A), Grid phase C current (A), Power factor (), Grid frequency (Hz), Active power (kW), Output reactive power (kvar), Daily energy (kWh), Total input power (kW), PV1 input voltage (V), PV2 input voltage (V), PV3 input voltage (V), PV4 input voltage (V), PV1 input current (A), PV2 input current (A), PV3 input current (A), PV4 input current (A), MPPT 1 DC cumulative energy (kWh), MPPT 2 DC cumulative energy (kWh)]
2021-10-07 23:52:13,949 Starting new HTTP connection (1): pvoutput.org:443
2021-10-07 23:52:14,314 https://pvoutput.org:443 "GET /service/r2/getstatus.jsp HTTP/1.1" 200 None
2021-10-07 23:52:14,321 Last data transfer to PV Output: 2021-10-06 08:00:00+02:00
2021-10-07 23:52:14,323 Starting new HTTPS connection (1): eu5.fusionsolar.huawei.com:443
2021-10-07 23:52:14,754 https://eu5.fusionsolar.huawei.com:443 "GET /rest/pvms/web/device/v1/device-history-data?signalIds=30004&signalIds=30005&signalIds=30006&signalIds=31001&signalIds=31004&signalIds=31007&signalIds=31010&deviceDn=NE%3DXXXXXXXX&date=1633500000000 HTTP/1.1" 200 None
2021-10-07 23:52:14,769 Single unit data for device NEXXXXXXXX 
```

But it stops later, as shown below
```
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    data = fusionsolar.query(device, starting_ts, signals)
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 187, in query
    single_unit_data = self.query_single_unit_2_days(device, date, subset)
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 205, in query_single_unit_2_days
    **self.query_single_unit(device, date.timestamp(), signals),
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 231, in query_single_unit
    {signal.get_code(): sample["counterValue"]}
  File "/home/dlaptop/Downloads/toolbelt/huawei-solar/api/fusionsolar.py", line 78, in get_code
    return self.name_to_code_map[self.name]
KeyError: 'PV3 input voltage'
```
