### ISSUE TITLE
Last commit `enforce_region_param` complains about schema

### ISSUE THREAD

**Issue by lampra1** [szczeles/toolbelt#22]
```
$ docker container logs c59365cd5e62
2022-01-04 22:54:32,304 Backing off call_api(...) for 0.2s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-RBW7gUmBGZubDZAP0dDG7TVTxHBqwMKGwaAsso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-RBW7gUmBGZubDZAP0dDG7TVTxHBqwMKGwaAsso?)
2022-01-04 22:54:33,106 Backing off call_api(...) for 0.6s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-WPURODLSF2k9FqvV3M2pjiYX7UNdvu6WjGDsso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-WPURODLSF2k9FqvV3M2pjiYX7UNdvu6WjGDsso?)
2022-01-04 22:54:34,441 Backing off call_api(...) for 2.2s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-oRC1OXFHxR7Jo3IY4DeuAdab0nlRctyoQkxsso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-oRC1OXFHxR7Jo3IY4DeuAdab0nlRctyoQkxsso?)
2022-01-04 22:54:37,310 Backing off call_api(...) for 7.1s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-MfkrPtmiAHJtbSB6yUDD7ybZfYWAzf3UraEsso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-MfkrPtmiAHJtbSB6yUDD7ybZfYWAzf3UraEsso?)
2022-01-04 22:54:45,086 Backing off call_api(...) for 2.7s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-txpNed1pHvebzKLNcm9UeiCAaTEzW6ALETlsso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-5-txpNed1pHvebzKLNcm9UeiCAaTEzW6ALETlsso?)
2022-01-04 22:54:48,247 Backing off call_api(...) for 14.8s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-lsgUIlqatAUoLeQerIvdeSdKC2hBPZVcesisso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-lsgUIlqatAUoLeQerIvdeSdKC2hBPZVcesisso?)
2022-01-04 22:55:03,729 Backing off call_api(...) for 10.3s (requests.exceptions.MissingSchema: Invalid URL '/unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-PiT2fX6zjdcmE92WemHanp4fm2vHm3smfl0sso': No schema supplied. Perhaps you meant http:///unisess/v1/auth?service=%2Fnetecowebext%2Fhome%2Findex.html&ticket=ST-7-PiT2fX6zjdcmE92WemHanp4fm2vHm3smfl0sso?)
```

**Comment by szczeles** [comment]
Hey @lampra1, thanks for the bug report. Please check if the code from `fix_base_url_call` helps in your case

**Comment by lampra1** [comment]
Hi @szczeles, thank you for your efforts. 
Logs **without** using '--fusionsolar-station-id NE='  

```
$ docker container logs c7980287a0b6
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    devices = fusionsolar.list_devices()
  File "/api/fusionsolar.py", line 174, in list_devices
    "conditionParams.parentDn": self.station_id or self.get_station_id()
  File "/api/fusionsolar.py", line 161, in get_station_id
    company_info = self.call_api("rest/neteco/web/organization/v2/company/current")
  File "/usr/local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/api/fusionsolar.py", line 105, in call_api
    self.login()
  File "/api/fusionsolar.py", line 154, in login
    self.session = session.cookies["bspsession"]
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='bspsession', domain=None, path=None"
```

Logs using '--fusionsolar-station-id NE='  

```
$ docker container logs 3cd5766d5235
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    devices = fusionsolar.list_devices()
  File "/api/fusionsolar.py", line 171, in list_devices
    devices = self.call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/api/fusionsolar.py", line 105, in call_api
    self.login()
  File "/api/fusionsolar.py", line 154, in login
    self.session = session.cookies["bspsession"]
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='bspsession', domain=None, path=None"
```

**Comment by szczeles** [comment]
Mhm, got it... What region do you use? Can you try `eu5`?

**Comment by lampra1** [comment]
Nice catch!! Thank you. I supposed that I had to use the new region format `region02eu5`. It works using just `eu5`

**Comment by szczeles** [comment]
Awesome! 

It looks like Huawei sharded `eu5` users into different servers, but the lib implements one special API call that returns the region. So in case they decide to move your account again, it should cover it automatically.
