### ISSUE TITLE
Error with pvoutput addbatchstatus API : HTTP 400 Bad request : Moon powered

### ISSUE THREAD

**Issue by jvanbouchaute** [szczeles/toolbelt#33]
Doing a first time setup and export to pvoutput, the upload API call addbatchstatus returns an error 400 : Moon powered. Looking at the pvoutput support forum it seems related to the fact that the time value in the csv data params is during nighttime, which is the case for me : 

 Pushing 287 records to PVOutput
2022-11-23 17:13:32,503 Starting new HTTPS connection (1): pvoutput.org:443
2022-11-23 17:13:33,123 https://pvoutput.org:443 "GET /service/r2/addbatchstatus.jsp?data=20221110%2C00%3A05%2C50%2C446%3B20221110%2C00%3A10%2C80%2C436%3B20221110%2C00%3A15%2C130%2C566%3B20221110%2C00%3A20%2C180%2C491%3B20221110%2C00%3A25%2C210%2C334%3B20221110%2C00%3A30%2C250%2C972%3B20221110%2C00%3A35%2C270%2C303%3B20221110%2C00%3A40%2C300%2C252%3B20221110%2C00%3A45%2C320%2C239
...

A30%2C660%2C162 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    output[1].save(data_to_push)
  File "/api/pvoutput.py", line 104, in save
    self.call_api("addbatchstatus", {"data": data})
  File "/usr/local/lib/python3.8/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/api/pvoutput.py", line 68, in call_api
    raise PVOutputBadRequestException(response.text)
api.pvoutput.PVOutputBadRequestException: Bad request 400: Moon Powered

URLdecoded data: 
data=20221110,00:05,50,446;20221110,00:10,80,436;20221110,00:15,130,566;20221110,00:20,180,491;20221110,00:25,210,334;20221110,00:30,250,972;20221110,00:35,270,303;20221110,00:40,300,252;20221110,00

Do i need to set some timezone / region parameter somewhere ?
My system setting in PVoutput has the correct timezone (Europe/Brussels). 

Krgds.

**Comment by szczeles** [comment]
@jvanbouchaute "Moon powered", what a nice easter egg from pvoutput maintainers!

It looks the data to push are invalid (values for middle of the night should look like `20221110,00:05,0,0`), so configuration of PVoutput is probably OK. How did you generate these? Using my huawei-solar/foxess-to-pvoutput scrapers or in some custom way?

**Comment by szczeles** [comment]
@jvanbouchaute Did you manage to figure out the cause of invalid date?
