### ISSUE TITLE
Does fusionsolar still work for anyone?

### ISSUE THREAD

**Issue by rvk01** [szczeles/toolbelt#38]
Does the fusionsolar script (huawei-solar/api/fusionsolar.py) still work for anyone? For me, the login procedure doesn't return a valid redirectURL anymore (=None). Only the respMultiRegionName comes with a ticket number (something with single login). But for me the script stopped working on about januari 21th 2024.

Already wrote to huawei to upgrade my account to API status but I think that needs to be done via the installer. In that case I would need to write my own script using their API.

But the script (via web login) doesn't seem to be working anymore (for me, unless someone van indicate it still works for them).

2024-01-27 19:16:02,358 Starting new HTTPS connection (1): eu5.fusionsolar.huawei.com:443
2024-01-27 19:16:02,751 https://eu5.fusionsolar.huawei.com:443 "GET /unisso/login.action HTTP/1.1" 200 None
2024-01-27 19:16:02,861 https://eu5.fusionsolar.huawei.com:443 "GET /unisso/pubkey HTTP/1.1" 200 None
2024-01-27 19:16:03,213 https://eu5.fusionsolar.huawei.com:443 "POST /unisso/v3/validateUser.action?service=%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fnetecowebext%252Fhome%252Findex.html&timeStamp=1706379362832&nonce=46466a7271524b4473786f4c71674438 HTTP/1.1" 200 None
2024-01-27 19:16:03,218 {'errorCode': '470', 'errorMsg': None, 'redirectURL': None, 'respMultiRegionName': ['-5', '/rest/dp/web/v1/auth/on-sso-credential-ready?ticket=ST-31571-UEO65DV1zeFSw4e7MkZHJfjvVwlSE6PhMRf&regionName=region003'], 'twoFactorStatus': None, 'verifyCodeCreate': False}
Traceback (most recent call last):
  File "/home/pi/fusion/./fusion.py", line 57, in <module>
    devices = fusionsolar.list_devices()
etc...

**Comment by szczeles** [comment]
@rvk01 I'm glad you noticed it, my PV generation is so low in winter that I forgot to check the status recently. As you said, it looks like Fusionsolar changed the login procedure again and their responses do not match the code indeed... 

I'm working on a fix, should be ready within 1-2h

**Comment by szczeles** [comment]
@rvk01 Please check the code in #39 - it works for me in eu5 region, but in case you use a different one, some adjustments may be needed

**Comment by rvk01** [comment]
> @rvk01 Please check the code in #39 - it works for me in eu5 region, but in case you use a different one, some adjustments may be needed

Yes, I'm in the eu5 region. But it still gives me some troubles.

```
pi@raspberrypi:~/fusion $ ./fusion.py
2024-01-29 10:25:57,118 Starting new HTTPS connection (1): eu5.fusionsolar.huawei.com:443
2024-01-29 10:25:57,512 https://eu5.fusionsolar.huawei.com:443 "GET /unisso/login.action HTTP/1.1" 200 None
2024-01-29 10:25:57,607 https://eu5.fusionsolar.huawei.com:443 "GET /unisso/pubkey HTTP/1.1" 200 None
2024-01-29 10:25:57,903 https://eu5.fusionsolar.huawei.com:443 "POST /unisso/v3/validateUser.action?service=%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fnetecowebext%252Fhome%252Findex.html&timeStamp=1706520357592&nonce=6a6346696c417267626c647a4d435578 HTTP/1.1" 200 None
2024-01-29 10:25:58,084 https://eu5.fusionsolar.huawei.com:443 "GET /rest/dp/web/v1/auth/on-sso-credential-ready?ticket=ST-48171-vIhV2XRnWeBPvrUtK6NskgKneAQO9pNQu9t&regionName=region003 HTTP/1.1" 302 0
2024-01-29 10:25:58,093 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
2024-01-29 10:25:58,466 https://uni003eu5.fusionsolar.huawei.com:443 "GET /uniportal/pvmswebsite/assets/build/cloud.html?app-id=smartpvms&instance-id=smartpvms&zone-id=region-3-80c6cfd2-f245-4d5a-9739-f7ac510fcd99 HTTP/1.1" 200 749
2024-01-29 10:25:58,470 Login successful, session: x-1c1h3zcbimhdum5glier1crshck95c7s5hbx1ig65fntsa4a1hpcip0bnxmqil7wnv48g96m9cjyep7sdg3uk7bwvvljqoql3svxlc9fqlg59h3w6ovvpfeoc9nutjnx, station: NE=34293475
2024-01-29 10:25:58,492 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
2024-01-29 10:25:58,958 https://uni003eu5.fusionsolar.huawei.com:443 "GET /rest/neteco/web/config/device/v1/device-list?conditionParams.parentDn=NE%3D34293475 HTTP/1.1" 406 141
2024-01-29 10:25:58,968 Backing off call_api(...) for 0.1s (fusionsolar.FusionSolarException: Invalid response code: 406, content: {"exceptionId":"access_denied","exceptionType":"ROA_EXFRAME_EXCEPTION","descArgs":null,"reasonArgs":null,"detailArgs":null,"adviceArgs":null})
2024-01-29 10:25:59,028 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
2024-01-29 10:25:59,500 https://uni003eu5.fusionsolar.huawei.com:443 "GET /rest/neteco/web/config/device/v1/device-list?conditionParams.parentDn=NE%3D34293475 HTTP/1.1" 406 141
2024-01-29 10:25:59,509 Backing off call_api(...) for 1.3s (fusionsolar.FusionSolarException: Invalid response code: 406, content: {"exceptionId":"access_denied","exceptionType":"ROA_EXFRAME_EXCEPTION","descArgs":null,"reasonArgs":null,"detailArgs":null,"adviceArgs":null})
2024-01-29 10:26:00,823 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
2024-01-29 10:26:01,300 https://uni003eu5.fusionsolar.huawei.com:443 "GET /rest/neteco/web/config/device/v1/device-list?conditionParams.parentDn=NE%3D34293475 HTTP/1.1" 406 141
2024-01-29 10:26:01,310 Backing off call_api(...) for 1.1s (fusionsolar.FusionSolarException: Invalid response code: 406, content: {"exceptionId":"access_denied","exceptionType":"ROA_EXFRAME_EXCEPTION","descArgs":null,"reasonArgs":null,"detailArgs":null,"adviceArgs":null})
2024-01-29 10:26:02,443 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
2024-01-29 10:26:02,970 https://uni003eu5.fusionsolar.huawei.com:443 "GET /rest/neteco/web/config/device/v1/device-list?conditionParams.parentDn=NE%3D34293475 HTTP/1.1" 406 141
2024-01-29 10:26:02,983 Backing off call_api(...) for 7.5s (fusionsolar.FusionSolarException: Invalid response code: 406, content: {"exceptionId":"access_denied","exceptionType":"ROA_EXFRAME_EXCEPTION","descArgs":null,"reasonArgs":null,"detailArgs":null,"adviceArgs":null})
2024-01-29 10:26:10,507 Starting new HTTPS connection (1): uni003eu5.fusionsolar.huawei.com:443
etc.
```

**Comment by szczeles** [comment]
Interesting... Error of type `access_denied` makes me feel like the station id is wrong maybe. Do you pass station id (`NE=34293475`) to the library? If yes, consider dropping it so it will autoresolve the available stations/devices

**Comment by rvk01** [comment]
> Interesting... Error of type `access_denied` makes me feel like the station id is wrong maybe. Do you pass station id (`NE=34293475`) to the library? If yes, consider dropping it so it will autoresolve the available stations/devices

YES. That fixes the problem (it's uploading now to pvoutput, will take a while because of the missed data). I didn't change anything to the stationd-id so it's weird that passing it would fail now. (I'll need to check if the id changed on their end.)

But I'm glad it works now. Thanks.

**Comment by szczeles** [comment]
It looks they changed the stations identifiers with the recent release - I located some old logs and it seems mine changed, too.

**Comment by rvk01** [comment]
Still not 100% stable. But with restarting the code it does continue.
For now... it'll do ;)

```
2024-01-29 12:10:04,721 Login successful, session: x-ipjutjcaditc2lfvo6tjtjfs4884ddg4epg7erc6jwldqnnw7ztchho9lc8bmmg6o9vyekg87zderxs4ep2mnz3w45cbqn2qirbw2q1ian2kfz44mmo8vtrtmm06gbsb, station: NE=137536878
Traceback (most recent call last):
  File "/home/pi/fusion/./fusion.py", line 83, in <module>
    data = fusionsolar.query(device, starting_ts, signals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/fusion/fusionsolar.py", line 240, in query
    single_unit_data = self.query_single_unit_2_days(device, date, subset)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/fusion/fusionsolar.py", line 258, in query_single_unit_2_days
    **self.query_single_unit(device, date.timestamp(), signals),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/fusion/fusionsolar.py", line 269, in query_single_unit
    data = self.call_api(
           ^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/fusion/fusionsolar.py", line 127, in call_api
    return self.call_api(endpoint, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/fusion/fusionsolar.py", line 116, in call_api
    func = getattr(requests, method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'dict'

```

**Comment by szczeles** [comment]
Yea, I noticed the same, it looks session lifetime is limited to 30 minutes now and indeed re-login implementation didn't work as expected. It's fixed now in `master` :-)

**Comment by rvk01** [comment]
Yes, it seems to keep going now.
Thanks.

**Comment by rvk01** [comment]
Has something changed again? It stopped working yesterday. It seems to be in a loop when logging in.

**Comment by szczeles** [comment]
Oh no, again? :-( It looks they added CSRF protection, this should fix it: https://github.com/szczeles/toolbelt/pull/43 - please have a look if it works @rvk01

**Comment by rvk01** [comment]
> Oh no, again? :-( It looks they added CSRF protection, this should fix it: #43 - please have a look if it works @rvk01

@szczeles  Yes. This fix seems to be working correctly for me. Thanks 👍

**Comment by szczeles** [comment]
@rvk01 I noticed that the current code causes re-login every ~30 minutes and calling keep-alive endpoint makes the problem disappear (session was alive almost 5h in my tests). The updated code is on #43 - please have a look. If it works in your env, I will merge it to master

**Comment by rvk01** [comment]
@szczeles Yes, it always did a re-login after 30 minutes (always has). The fix for CSRF is working now for 3 days. Now running the latest with keep-alive. I'll let you know in the morning if it's still running without re-logins.

**Comment by rvk01** [comment]
@szczeles It seems to work stable here. No re-logins since yesterday evening and updates to pvoutput are ok. So the keep-alive is working too.

**Comment by djsuszi** [comment]
for me it also works fine now

**Comment by szczeles** [comment]
@rvk01 @djsuszi Thanks for checking, guys!
